name: Team Approval workflow
on: pull_request_review

jobs:
  labelWhenAprroved:
    runs-on: ubuntu-latest
    steps:
    - name: Label approved all requests
      uses: abinoda/label-when-approved-action@1.0.5
      env:
        APRROVALS: "1"
        GITHUb_TOKENS: ${{ secrets.GITHUB_TOKEN}}
        ADD_LABEL: "approved"
  
